Add Mayhem support
mayhemheroes/skipper pull request #1
Opened 2022-05-15 19:17 UTC by mahaloz

2022-05-29 22:00 UTC, xansec requested changes

2022-05-31 23:37 UTC, mahaloz commented on Dockerfile
> +from golang:1.17 as builder
Hey @xansec would you be able to give some advice on how you can do this in the mayhem.yml file? Mostly just specifying which docker file to build, since I see no explicit build command.

2022-05-31 23:54 UTC, xansec commented on Dockerfile
> +from golang:1.17 as builder
You can add a `file` parameter to the Docker build stage. So this:
```
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
   ```
   Would look like this:
   ```
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: path/to/my/Dockerfile.custom
   ```

2022-06-03 22:47 UTC, mahaloz commented on Dockerfile
> +from golang:1.17 as builder
alright done!

2022-06-03 22:48 UTC, mahaloz commented
@xansec I've made the requested changes

2022-06-04 04:50 UTC, xansec commented
LGTM!

2022-06-04 04:51 UTC, merged